# Generated by Django 6.0.2 on 2026-04-08 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='cart_item_ids',
            field=models.JSONField(default=list),
        ),
    ]
