# Generated by Django 6.0.2 on 2026-04-22 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0002_category_tour_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='info_file',
            field=models.FileField(blank=True, help_text='File text (.txt) chứa thông tin chi tiết về địa điểm này', null=True, upload_to='destinations/info/'),
        ),
    ]
