# Generated by Django 6.0.2 on 2026-04-22 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0003_destination_info_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='keywords',
            field=models.TextField(blank=True, help_text='Các từ khóa liên quan, cách nhau bằng dấu phẩy (vd: thành phố sương mù, cao nguyên)', null=True),
        ),
    ]
