# Generated by Django 6.0.2 on 2026-04-14 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_alter_booking_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='show_on_calendar',
            field=models.BooleanField(default=True, verbose_name='Hiển thị trên lịch'),
        ),
        migrations.AddField(
            model_name='cart',
            name='show_on_calendar',
            field=models.BooleanField(default=True, verbose_name='Hiển thị trên lịch'),
        ),
    ]
