# Generated by Django 4.2.30 on 2026-04-19 04:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_type', models.CharField(choices=[('FORGOT_PASSWORD', 'Quên mật khẩu'), ('REFUND', 'Hoàn tiền'), ('EDIT_INFO', 'Chỉnh sửa thông tin'), ('OTHER', 'Khác')], default='FORGOT_PASSWORD', max_length=20)),
                ('content', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PROCESSING', 'Đang xử lý'), ('COMPLETED', 'Đã hoàn thành')], default='PROCESSING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='support_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
