# Generated by Django 4.2.30 on 2026-04-19 04:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportrequest',
            name='guest_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='supportrequest',
            name='guest_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='supportrequest',
            name='request_type',
            field=models.CharField(choices=[('FORGOT_PASSWORD', 'Quên mật khẩu'), ('REFUND', 'Hoàn tiền'), ('EDIT_INFO', 'Chỉnh sửa thông tin'), ('CONTACT', 'Liên hệ hỗ trợ'), ('OTHER', 'Khác')], default='CONTACT', max_length=20),
        ),
        migrations.AlterField(
            model_name='supportrequest',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='support_requests', to=settings.AUTH_USER_MODEL),
        ),
    ]
